# Generated by Django 2.1.5 on 2019-01-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ttemplate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='telefone',
        ),
    ]
